name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Create a writable directory for the SQLite database
    - name: Set up writable directory
      run: mkdir -p ${{ runner.temp }}/database

    # Copy the SQLite database to the writable directory
    - name: Copy SQLite database
      run: cp example/bdata.sqlite3 ${{ runner.temp }}/database/
    - name: Copy secondary SQLite database
      run: cp example/tdata.sqlite3 ${{ runner.temp }}/database/
    - name: Set up Django settings
      run: |
        echo "DATABASES = {
            'bdata': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': '${{ runner.temp }}/database/bdata.sqlite3',
            }
            'tdata': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': '${{ runner.temp }}/database/tdata.sqlite3',
            },
        }" >> ./vercel_app/settings.py

    - name: Run tests
      run: |
        python manage.py test
